# Mod properties
version = 26.1.0.0
mod_id = aromaaffect
mod_name = Aroma Affect
group = com.ovrtechnology
description = A Minecraft mod that brings the sense of smell to your gameplay through OVR scent hardware integration.

# Optional metadata
homepage = https://ovrtechnology.com/
sources = https://github.com/MoodStudios/aroma-affect
issues = https://github.com/MoodStudios/aroma-affect/issues
license = MIT
mod_author = Mood Studios, OVR Technology
credits =

# Build properties
java_version = 25
include_fabric = true
include_neoforge = true

# Gradle properties
org.gradle.jvmargs = -Xmx3G --enable-native-access=ALL-UNNAMED
org.gradle.parallel = true
org.gradle.daemon = false
